name: CD - Deploy Docker Image

on:
  repository_dispatch:
    types: [trigger-cd]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker pull ${{ vars.DOCKER_USERNAME }}/mi-app-angular:$VERSION

      - name: Deploy to Nginx
        run: |
          docker run -d -p 80:80 ${{ vars.DOCKER_USERNAME }}/mi-app-angular:$VERSION
          curl -f http://localhost:80 || exit 1
