name: CI - Build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo 'npm test'

      - name: Build Angular application
        run: npm run build --prod

      - name: Build Docker image
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker build -t ${{ vars.DOCKER_USERNAME }}/mi-app-angular:$VERSION .

      - name: Push Docker image
        run: |
          docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          VERSION=$(node -p "require('./package.json').version")
          docker push ${{ vars.DOCKER_USERNAME }}/mi-app-angular:$VERSION

  post-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CD workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-cd




